services:
  app:
    build: .
    container_name: lasorianita
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: matching-matcha-web-nextjs_default
